# Generated by Django 2.1.3 on 2018-12-03 16:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundName', models.CharField(max_length=30)),
                ('backgrounFeats', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('backgrounItems', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('backgrounProficiencies', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.CreateModel(
            name='Adventurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advName', models.CharField(max_length=30)),
                ('alignment', models.CharField(blank=True, max_length=2)),
                ('experience', models.PositiveIntegerField(blank=True)),
                ('advClass', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('advFeats', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('advItems', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('stats', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('skills', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('personalityTraits', models.TextField(blank=True)),
                ('ideals', models.TextField(blank=True)),
                ('bonds', models.TextField(blank=True)),
                ('flaws', models.TextField(blank=True)),
                ('inspiration', models.SmallIntegerField(blank=True)),
                ('size', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AdventurerClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=30)),
                ('classFeats', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('classItems', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('classProficiencies', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.CreateModel(
            name='AdventurerRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raceName', models.CharField(max_length=30)),
                ('raceFeats', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('statMod', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('raceProficiencies', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=30)),
                ('itemDescription', models.TextField(blank=True)),
                ('armorMod', models.SmallIntegerField(blank=True)),
                ('statMod', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('speedMod', models.SmallIntegerField(blank=True)),
                ('initiativeMod', models.SmallIntegerField(blank=True)),
                ('weaponDamage', models.CharField(blank=True, max_length=30)),
                ('weaponTraits', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featName', models.CharField(max_length=30)),
                ('featDescription', models.TextField()),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiencyName', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='adventurer',
            name='advRace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.AdventurerRace'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile'),
        ),
    ]
