# Generated by Django 2.1.3 on 2018-12-03 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181203_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spellName', models.CharField(max_length=50)),
                ('spellDescription', models.TextField()),
                ('spellLevel', models.PositiveSmallIntegerField()),
                ('spellCastTime', models.CharField(max_length=50)),
                ('spellRange', models.CharField(max_length=100)),
                ('spellComponents', models.TextField()),
                ('spellDuration', models.CharField(max_length=50)),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='armorMod',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='initiativeMod',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='speedMod',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='statMod',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='weaponDamage',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='weaponTraits',
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='itemRarity',
            field=models.CharField(default='Common', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='userName',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adventurebackground',
            name='backgroundName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adventurer',
            name='advName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adventurerclass',
            name='className',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adventurerrace',
            name='raceName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='itemDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='itemName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feat',
            name='featName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='proficiencyName',
            field=models.CharField(max_length=50),
        ),
    ]
