# Generated by Django 2.1.3 on 2018-12-03 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20181203_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentitem',
            name='userName',
        ),
    ]
