# Generated by Django 2.1.3 on 2018-12-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_equipmentitem_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feat',
            old_name='featName',
            new_name='name',
        ),
    ]
