# Generated by Django 2.1.3 on 2018-12-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20181203_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentitem',
            old_name='itemName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='spell',
            old_name='spellName',
            new_name='name',
        ),
    ]
