# Generated by Django 2.1.3 on 2018-12-04 14:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20181203_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventurerrace',
            old_name='raceName',
            new_name='name',
        ),
        migrations.AddField(
            model_name='adventurerrace',
            name='raceSize',
            field=models.CharField(default='medium', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adventurerrace',
            name='raceSpeed',
            field=models.CharField(default='30 feet', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adventurerrace',
            name='raceSpells',
            field=models.CharField(default='0', max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adventurerrace',
            name='userName',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile'),
            preserve_default=False,
        ),
    ]
