# Generated by Django 2.1.3 on 2018-12-04 22:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20181204_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventurerClassLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('classFamily', models.CharField(max_length=50)),
                ('classDescription', models.TextField()),
                ('classProfciencyBonus', models.PositiveSmallIntegerField()),
                ('classLevel', models.PositiveSmallIntegerField()),
                ('classHitDice', models.CharField(max_length=50)),
                ('classFeats', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('classSpells', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('classItems', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('classProficiencies', models.TextField()),
                ('classClasses', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile')),
            ],
        ),
        migrations.DeleteModel(
            name='AdventureBackground',
        ),
        migrations.DeleteModel(
            name='AdventurerClass',
        ),
    ]
