# Generated by Django 2.1.3 on 2018-12-04 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20181204_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventurerclasslevel',
            old_name='classSpells',
            new_name='classSpellslots',
        ),
        migrations.RemoveField(
            model_name='adventurerclasslevel',
            name='classClasses',
        ),
    ]
