# Generated by Django 2.1.3 on 2018-12-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20181204_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventurerclasslevel',
            old_name='classProfciencyBonus',
            new_name='classProficiencyBonus',
        ),
    ]
