# Generated by Django 2.1.3 on 2018-12-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20181204_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proficiency',
        ),
        migrations.RenameField(
            model_name='adventurer',
            old_name='advName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='adventurer',
            name='alignment',
        ),
        migrations.RemoveField(
            model_name='adventurer',
            name='bonds',
        ),
        migrations.RemoveField(
            model_name='adventurer',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='adventurer',
            name='flaws',
        ),
        migrations.RemoveField(
            model_name='adventurer',
            name='ideals',
        ),
        migrations.RemoveField(
            model_name='adventurer',
            name='inspiration',
        ),
        migrations.RemoveField(
            model_name='adventurer',
            name='personalityTraits',
        ),
        migrations.RemoveField(
            model_name='adventurer',
            name='size',
        ),
        migrations.RemoveField(
            model_name='adventurer',
            name='skills',
        ),
        migrations.AddField(
            model_name='adventurer',
            name='advBackground',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
