# Generated by Django 2.1.3 on 2018-12-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20181204_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AlterField(
            model_name='spell',
            name='spellRange',
            field=models.CharField(max_length=50),
        ),
    ]
